### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by reinethernal** [popstas/yandex-speechkit-talk-recognition#1]
root@stt:~/yandex-stt# yandex-stt --file /root/audio/levitan.wav
(node:21765) UnhandledPromiseRejectionWarning: ReferenceError: fileToRecognize is not defined
    at start (/root/.npm-global/lib/node_modules/yandex-speechkit-talk-recognition/index.js:57:20)
    at Object.<anonymous> (/root/.npm-global/lib/node_modules/yandex-speechkit-talk-recognition/index.js:77:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:21765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by reinethernal** [comment]
cat /etc/issue
Ubuntu 18.04.6 LTS \n \l

root@stt:~ # node -v
v14.18.0
root@stt:~ #  npm -v
8.0.0
root@stt:~#

**Comment by reinethernal** [comment]
Забыл добавить. Всё это крутится на lxc на непривилигированном контейнере.

**Comment by reinethernal** [comment]
Перенёс на виртуалку. Та же история.

root@stt:/usr/lib/node_modules/yandex-speechkit-talk-recognition# yandex-stt --file levitan.wav
/usr/lib/node_modules/yandex-speechkit-talk-recognition/index.js:57
    const resRec = await fileToRecognize(options.file);
                   ^

ReferenceError: fileToRecognize is not defined
    at start (/usr/lib/node_modules/yandex-speechkit-talk-recognition/index.js:57:20)
    at Object.<anonymous> (/usr/lib/node_modules/yandex-speechkit-talk-recognition/index.js:77:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
root@stt:/usr/lib/node_modules/yandex-speechkit-talk-recognition#

**Comment by reinethernal** [comment]
Собственно ни на 16 ни на 14 версии ноды не работает, смена типа виртуализации так же не помогла((

**Comment by reinethernal** [comment]
То ли лыжи не едут, то ли я на асфальте. Ни один из вариантов что пробовал не помогает(((
